create extension if not exists pgcrypto;

create table if not exists public.books (
  id text primary key,
  title text not null,
  age_range text not null default '',
  description text not null default '',
  amazon_url text not null,
  asin text not null,
  cover_url text not null,
  tags text[] not null default '{}',
  sort_order integer not null default 0,
  featured boolean not null default false,
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  book_id text references public.books(id) on delete set null,
  path text not null default '',
  referrer text not null default '',
  user_agent text not null default '',
  device text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_books_visible_sort
on public.books (visible, sort_order);

create index if not exists idx_analytics_type_created
on public.analytics_events (event_type, created_at);

create index if not exists idx_analytics_book_created
on public.analytics_events (book_id, created_at);

alter table public.books enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "Public can read visible books" on public.books;
create policy "Public can read visible books"
on public.books
for select
to anon, authenticated
using (visible = true);

insert into public.books
  (id, title, age_range, description, amazon_url, asin, cover_url, tags, sort_order, featured, visible)
values
  (
    'princess-adventure-3-8',
    'Princess Adventure Coloring Book: Ages 3-8',
    'Ages 3-8',
    'Fun and easy coloring pages with cute princesses, castles, unicorns, fairies, and magical adventures.',
    'https://www.amazon.com/dp/B0H32C3M4K',
    'B0H32C3M4K',
    '/assets/cover-B0H32C3M4K.jpg',
    array['Princesses', 'Unicorns', 'Ages 3-8'],
    10,
    true,
    true
  ),
  (
    'baby-animals-3-8',
    'Baby Animals Coloring Book: Ages 3-8',
    'Ages 3-8',
    'Easy coloring pages for young kids who love sweet puppies, kittens, bunnies, pandas, lions, elephants, and ducks.',
    'https://www.amazon.com/dp/B0H7MTZ9S8',
    'B0H7MTZ9S8',
    '/assets/cover-B0H7MTZ9S8.jpg',
    array['Baby animals', 'Easy pages', 'Ages 3-8'],
    20,
    true,
    true
  ),
  (
    'princess-adventure-3-6',
    'Princess Adventure Coloring Book: Ages 3-6',
    'Ages 3-6',
    'A beginner-friendly princess coloring book for preschoolers, toddlers, and early learners who enjoy magical scenes.',
    'https://www.amazon.com/dp/B0H29NPB7N',
    'B0H29NPB7N',
    '/assets/cover-B0H29NPB7N.jpg',
    array['Preschool', 'Simple designs', 'Ages 3-6'],
    30,
    false,
    true
  ),
  (
    'prince-adventure-3-8',
    'Prince Adventure Coloring Book: Ages 3-8',
    'Ages 3-8',
    'Brave princes, castles, dragons, knights, and magical adventures for kids who like quest-themed coloring pages.',
    'https://www.amazon.com/dp/B0H323CLFD',
    'B0H323CLFD',
    '/assets/cover-B0H323CLFD.jpg',
    array['Princes', 'Dragons', 'Ages 3-8'],
    40,
    false,
    true
  )
on conflict (id) do update set
  title = excluded.title,
  age_range = excluded.age_range,
  description = excluded.description,
  amazon_url = excluded.amazon_url,
  asin = excluded.asin,
  cover_url = excluded.cover_url,
  tags = excluded.tags,
  sort_order = excluded.sort_order,
  featured = excluded.featured,
  visible = excluded.visible,
  updated_at = now();
